#!/bin/sh

cd "$(git rev-parse --show-toplevel)"

ESLINT="node_modules/.bin/eslint"
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$")


if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[41mPlease install Eslint\033[0m\n"
  exit 1
fi

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

echo "Validating ${#STAGED_FILES} files"

for FILE in $STAGED_FILES
do
  "$ESLINT" "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    printf "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done


if ! $PASS; then
  printf "\033[41mCOMMIT FAILED:\033[0m.\n"
  exit 1
else
  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?